# This file is meant for use with the scripting mode enabled

FROM registry.access.redhat.com/ubi9/go-toolset:1.21.10 as builder

ENV VERSION="1.21"

WORKDIR /opt/app-root
COPY . .

RUN go build -ldflags "-X main.version=${VERSION}" -mod vendor -o node-observability-agent cmd/node-observability-agent/main.go

FROM registry.access.redhat.com/ubi9/ubi-init:latest

# taken from KCS article https://access.redhat.com/solutions/5343671
RUN dnf install -y tc perf psmisc hostname sysstat iotop conntrack-tools ethtool numactl net-tools

RUN mkdir -p /tmp/scripts && mkdir -p /tmp/results 
COPY --from=builder /opt/app-root/node-observability-agent /usr/bin/
COPY scripts/metrics/* /tmp/scripts
COPY ./uid_entrypoint.sh ./uid_entrypoint.sh

EXPOSE 9000

# this allows us to set the command and args in the deploy config
# ./node-observability-agent --mode scripting --storage results --loglevel debug
ENTRYPOINT ["./uid_entrypoint.sh"]
