apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-observability-agent
spec:
  template:
    spec:
      containers:
      - name: node-observability-agent
        securityContext:
          privileged: true 
