apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    openshift.io/scc: hostaccess
  name: node-observability-agent
spec:
  template:
    spec:
      containers:
      - args:
        - --tokenFile=/var/run/secrets/kubernetes.io/serviceaccount/token
        - --storage=/run
        - --caCertFile=/var/run/secrets/kubelet-serving-ca/ca-bundle.crt
        command:
        - node-observability-agent
        env:
        - name: NODE_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        image: node-observability-agent:latest
        imagePullPolicy: IfNotPresent
        name: node-observability-agent
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /var/run/crio/crio.sock
          name: socket
        - mountPath: /var/run/secrets/kubelet-serving-ca/
          name: kubelet-ca
          readOnly: true
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:9000/
        - --tls-cert-file=/var/run/secrets/openshift.io/certs/tls.crt
        - --tls-private-key-file=/var/run/secrets/openshift.io/certs/tls.key
        - --logtostderr=true
        - --v=2
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.11.0
        imagePullPolicy: IfNotPresent
        name: kube-rbac-proxy
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/run/secrets/openshift.io/certs
          name: certs
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: node-observability-agent
      serviceAccountName: node-observability-agent
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /var/run/crio/crio.sock
          type: Socket
        name: socket
      - configMap:
          defaultMode: 420
          name: node-observability-agent
        name: kubelet-ca
      - name: certs
        secret:
          defaultMode: 420
          secretName: node-observability-agent
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
