---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-observability-agent-scc
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - node-observability-agent
  resources:
  - securitycontextconstraints
  verbs:
  - use
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/proxy
  - pods
  verbs:
  - get
  - list

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-observability-agent-scc-rb
subjects:
- kind: ServiceAccount
  name: $(SERVICE_ACCOUNT_NAME)
roleRef:
  kind: Role
  name: node-observability-agent-scc
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-observability-agent-scc
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - node-observability-scc
  resources:
  - securitycontextconstraints
  verbs:
  - use
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/proxy
  - pods
  verbs:
  - get
  - list
- nonResourceURLs:
  - /node-observability-status
  - /node-observability-pprof
  verbs:
  - get
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-observability-agent-scc-crb
subjects:
- kind: ServiceAccount
  name: $(SERVICE_ACCOUNT_NAME)
  namespace: $(SERVICE_ACCOUNT_NAMESPACE)
roleRef:
  kind: ClusterRole
  name: node-observability-agent-scc
  apiGroup: rbac.authorization.k8s.io
