apiVersion: v1
kind: Service
metadata:
  name: node-observability-agent
  annotations: 
    "service.beta.openshift.io/serving-cert-secret-name": "node-observability-agent"
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: nodeobservability
    nodeobs_cr: nodeobservability-sample
  sessionAffinity: None
  type: ClusterIP

